### ISSUE TITLE
Support SYNONYMs in CREATE TABLE

### ISSUE THREAD

**Issue by apstndb** [cloudspannerecosystem/memefish#125]
`SYNONYM`s in `CREATE TABLE` has not yet been supported.

https://cloud.google.com/spanner/docs/reference/standard-sql/data-definition-language#create_table
```
CREATE TABLE [ IF NOT EXISTS ] table_name ( [
   { column_name data_type [NOT NULL]
     [ { DEFAULT ( expression ) | AS ( expression ) [ STORED ]
       | table_constraint | synonym_definition ]
     [ options_def ]
     [ location_name STRING(MAX) NOT NULL PLACEMENT KEY ]
   [, ... ]
] ) PRIMARY KEY ( [column_name [ { ASC | DESC } ], ...] )
[, INTERLEAVE IN PARENT table_name [ ON DELETE { CASCADE | NO ACTION } ] ]
[, ROW DELETION POLICY ( OLDER_THAN ( timestamp_column, INTERVAL num_days DAY ) ) ]

...

and synonym_definition is:
    [ SYNONYM (synonym [, synonym...])]
```
Related: #115

**Comment by apstndb** [comment]
I have curious about what is displayed in [`getDdl`](https://cloud.google.com/spanner/docs/reference/rest/v1/projects.instances.databases/getDdl) or [`gcloud spanner databases ddl describe`](https://cloud.google.com/sdk/gcloud/reference/spanner/databases/ddl/describe) after adding multiple `SYNONYM`s

**Comment by apstndb** [comment]
I have noticed there are no `[ALTER TABLE ALTER COLUMN ADD SYNONYM](https://cloud.google.com/spanner/docs/reference/standard-sql/data-definition-language#alter_table)`.
There is only `ALTER TABLE ADD SYNONYM synonym` and `ALTER TABLE RENAME TO new_table_name`.

**Comment by makenowjust** [comment]
The last expression in the screen shot is failed, and I guess only the last synonym is available.

<img width="422" alt="スクリーンショット 2024-10-19 22 51 03" src="https://github.com/user-attachments/assets/11a4e19c-f670-4a26-a2ad-c4f5565de924">

**Comment by apstndb** [comment]
```
spanner> CREATE TABLE t(PK INT64, SYNONYM(alias1)) PRIMARY KEY(PK);
Query OK, 0 rows affected (6.78 sec)

spanner> SHOW CREATE TABLE t;
+-------+--------------------+
| Table | Create Table       |
+-------+--------------------+
| t     | CREATE TABLE t (   |
|       |   PK INT64,        |
|       |   SYNONYM(alias1), |
|       | ) PRIMARY KEY(PK)  |
+-------+--------------------+
1 rows in set (0.80 sec)

spanner> ALTER TABLE t ADD SYNONYM alias2;
ERROR: rpc error: code = FailedPrecondition desc = Cannot add a synonym t for alias2. A synonym already exists for this table.
```

**Comment by apstndb** [comment]
```
spanner> CREATE TABLE t2(PK INT64, SYNONYM(alias21), SYNONYM(alias22)) PRIMARY KEY(PK);
Query OK, 0 rows affected (7.51 sec)

spanner> SHOW CREATE TABLE t2;
+-------+---------------------+
| Table | Create Table        |
+-------+---------------------+
| t2    | CREATE TABLE t2 (   |
|       |   PK INT64,         |
|       |   SYNONYM(alias22), |
|       | ) PRIMARY KEY(PK)   |
+-------+---------------------+
1 rows in set (0.77 sec)
```

Only last synonym is enabled.

**Comment by apstndb** [comment]
I don't think it is documented behavior. I will feed back to Google.

**Comment by apstndb** [comment]
I have noticed the documented DDL syntax is fixed.

https://cloud.google.com/spanner/docs/reference/standard-sql/data-definition-language#create_table

```
and synonym_definition is:
    [ SYNONYM (synonym) ]
```
