### ISSUE TITLE
Generalize OPTIONS behavior

### ISSUE THREAD

**Issue by apstndb** [cloudspannerecosystem/memefish#137]
Currently, memefish fails unknown option key in some `OPTIONS`.
`OPTIONS` key can be added without notification, and it is even possible to have undocument options.

I think it is better to have "schema on read" semantics rather than "schema on write(parse)" semantics.
Validation should be the responsibility of semantic analysis phase.

Proposed characteristics

* Any key-value pairs can be parsed and unparsed.
* Known key-value can be accessed by named methods.
  * It can be error if invalid value type, and the error can be handled.
  * These are maintained on a best effort basis.
* Concrete options share underlying implementation as `GenericOptions`.

**Comment by apstndb** [comment]
Implement proposed behavior in #111

**Comment by makenowjust** [comment]
As said in https://github.com/cloudspannerecosystem/memefish/pull/122#discussion_r1804209426, we can change AST definitions. Thus, we have another idea to introduce a new `Options`, the same as `GenericOptions`, and to replace existing `XXXOptions` types with this. In this case, we need to introduce the following utility functions.

```go
func (o *Options) BoolField(name string) (bool, error) { ... }
func (o *Options) StringField(name string) (bool, error) { ... }
// ..., `IntField`, `FloatField`, and more.
```

(I'm not sure "field" is correct naming.)

**Comment by apstndb** [comment]
I have researched documented options in [GoogleSQL data definition language](https://cloud.google.com/spanner/docs/reference/standard-sql/data-definition-language).
object_type | option_name | option_type
-- | -- | --
DATABASE | default_leader | STRING
DATABASE | optimizer_version | INTEGER
DATABASE | optimizer_statistics_package | STRING
DATABASE | version_retension_perios | STRING
PLACEMENT | instance_partition | STRING
PLACEMENT | default_leader | STRING
COLUMN | allow_commit_timestamp | BOOL
SEARCH INDEX | sort_order_sharding | BOOL
SEARCH INDEX | disable_automatic_uid_column | BOOL
CHANGE STREAM | retention_period | STRING
CHANGE STREAM | value_capture_type | STRING
CHANGE STREAM | exclude_ttl_deletes | BOOL
CHANGE STREAM | exclude_insert | BOOL
CHANGE STREAM | exclude_update | BOOL
CHANGE STREAM | exclude_delete | BOOL
STATISTICS | allow_gc | BOOL
MODEL | endpoint | STRING
MODEL | endpoints | ARRAY&lt;STRING&gt;
MODEL | default_batch_size | INTEGER
VECTOR INDEX | distance_type | INTEGER
VECTOR INDEX | tree_depth | INTEGER
VECTOR INDEX | num_leaves | INTEGER
VECTOR INDEX | num_branches | INTEGER

`IntegerField`, `StringField`, `BoolField` cover all usecases except `endpoints`.
I think `ArrayStringField` is not needed.

* Provide `(*Options).Field(string) (Expr, bool)`
* Manually find using `Options.Records []*OptionsRecord`

I think it is not bad idea to provide `Field` method because it is possible that a new key-value pair have other type.

**Comment by apstndb** [comment]
Ok, I'll make another PR to add `Options` and migrate existing options to `Options`.
