### ISSUE TITLE
Support function hints

### ISSUE THREAD

**Issue by neglect-yp** [cloudspannerecosystem/memefish#198]
Function hints are not yet supported.

https://cloud.google.com/spanner/docs/reference/standard-sql/functions-reference#function_hints

```
$ go run ./tools/parse --mode query "SELECT
  SUBSTRING(CAST(x AS STRING), 2, 5) AS w,
  SUBSTRING(CAST(x AS STRING), 3, 7) AS y
FROM (SELECT SHA512(z) @{DISABLE_INLINE = TRUE} AS x FROM t)"
2024/11/12 23:35:16 syntax error: :4:24: expected token: ), but: @

  4:  FROM (SELECT SHA512(z) @{DISABLE_INLINE = TRUE} AS x FROM t)
                             ^
exit status 1
```

**Comment by apstndb** [comment]
## Research of ZetaSQL
function hint is implemented in `ASTFunctionCall` (`memefish/ast.CallExpr` equivalent)

https://github.com/google/zetasql/blob/a516c6b26d183efc4f56293256bba92e243b7a61/zetasql/parser/zetasql.tm#L10293-L10294

https://github.com/google/zetasql/blob/a516c6b26d183efc4f56293256bba92e243b7a61/zetasql/parser/gen_parse_tree.py#L2815-L2824
