### ISSUE TITLE
Maybe better to provide (*ast.Path).AsIdent

### ISSUE THREAD

**Issue by apstndb** [cloudspannerecosystem/memefish#244]
There is a frequent pattern of checking the path is constructed by one level, and get the element.
https://github.com/cloudspannerecosystem/yo/blob/44c1d636a3cb215cbf4e45893496770b536b032e/v2/loader/schema_parser_source.go#L33-L38

https://github.com/apstndb/memebridge/blob/ef1bc63e35abe326b60ea69ef722c49ad0bf9138/meme_to_sppb_value.go#L154

Maybe better to provide convenient method like `func (*ast.Path) AsIdent() (*ast.Ident, bool)`.

Note: Is it nice to have `func (*ast.Ident).EqualFold(string) bool` also?

**Comment by makenowjust** [comment]
`EqualFold` sounds good :+1:.

On the other hand, I have some opinions about `AsIdent`. Due to the `yo` example and its type signature, I guess your `AsIdent` is the following:

```go
func (p *ast.Path) AsIdent() (*ast.Ident, bool) {
  if len(p.Idents) != 1 {
    return nil, false
  }
  return p.Idents[0], true
}
```

However, I'm not sure this impl. is useful in the real world because `yo` has not yet supported schema. In my opinion, we need these methods actually:

- `func (*ast.Path) AsIdent() *ast.Ident`; it returns an ident `` `foo.bar.baz` `` (concatenation of all parts of the path with dots) from a path `foo.bar.baz`,
- `func (*ast.Path) AsNameIdent() *ast.Ident`; it returns an ident `` `baz` `` (the last part of the path) from a path `foo.bar.baz`, and
- `func (*ast.Path) AsSchemaIdent() *ast.Ident`; it returns an ident `` `foo.bar` `` (the path except for the last part) from a path `foo.bar.baz`.

Names are just my thinking.

**Comment by makenowjust** [comment]
We may need to introduce a new AST node for `SAFE`-prefixed calls. On this modification, does a distinction between `` `schema.name` `` and `` `schema`.`name` `` arise?

**Comment by apstndb** [comment]
I don't think `SAFE.` prefixed calls are parser level structure. I suggests it only for helper method in `*ast.CallExpr` node.

``SAFE.TO_JSON(1)`` and `` `SAFE`.TO_JSON(1) `` is same expression.
```
spanner> SELECT SAFE.TO_JSON(1), `SAFE`.TO_JSON(1);
+------+------+
|      |      |
| JSON | JSON |
+------+------+
| 1    | 1    |
+------+------+
1 rows in set (1.162125ms)
```

It is also same in ZetaSQL.

```
$ docker run --rm --platform linux/amd64 zetasql_ubuntu execute_query --product_mode=external --mode=parse 'SELECT SAFE.TO_JSON(1), `SAFE`.TO_JSON(1)' 
QueryStatement [0-41]
  Query [0-41]
    Select [0-41]
      SelectList [7-41]
        SelectColumn [7-22]
          FunctionCall [7-22]
            PathExpression [7-19]
              Identifier(SAFE) [7-11]
              Identifier(TO_JSON) [12-19]
            IntLiteral(1) [20-21]
        SelectColumn [24-41]
          FunctionCall [24-41]
            PathExpression [24-38]
              Identifier(SAFE) [24-30]
              Identifier(TO_JSON) [31-38]
            IntLiteral(1) [39-40]
```

I don't think it is enough reason to introduce new AST node for this semantic level reason.

**Comment by apstndb** [comment]
Another example of the distinction between `` `schema.name` `` and `` `schema`.`name` ``.

spanner> CREATE TABLE `sch1.tbl3` (PK INT64) PRIMARY KEY(PK);
ERROR: error on create op: rpc error: code = InvalidArgument desc = Error parsing Spanner DDL statement: CREATE TABLE `sch1.tbl3` (PK INT64) PRIMARY KEY (PK) : Error on line 1, column 14: Can not contain dot(.) in identifier: sch1.tbl3
spanner> CREATE TABLE `sch1`.`tbl3` (PK INT64) PRIMARY KEY(PK);
Query OK, 0 rows affected (8.30 sec)
timestamp:      2024-12-24T01:55:30.524756Z

**Comment by makenowjust** [comment]
Okay. I understand Google's implementation is broken, and it is hard to provide a good utility for paths. Let's close this issue.

**Comment by apstndb** [comment]
I don't agree your conclusion.

**Comment by apstndb** [comment]
My opinion is that.

> It is better to use `[]*ast.Ident` directly, or it is OK to provide just single `string`.
I think that `func (*ast.Path) AsString() string` may be useful.

It is similar to `FullName`s in ZetaSQL.
https://github.com/search?q=repo%3Agoogle%2Fzetasql+fullname&type=code

**Comment by makenowjust** [comment]
Please create a new issue. (I think `FullName` is a better name.)
