### ISSUE TITLE
Rename `SchemaType` to `DataType`

### ISSUE THREAD

**Issue by makenowjust** [cloudspannerecosystem/memefish#245]
Currently, we use `SchemaType` for types of columns in DDLs.
However, this kind of type is named `data_type` in the GoogleSQL document ([here](https://cloud.google.com/spanner/docs/reference/standard-sql/data-definition-language#create_table)).

```
where data_type is:
    { scalar_type | array_type | proto_type_name }
```

Then, we need to rename `SchemaType` to `DataType` to avoid this inconsistency.

**Comment by apstndb** [comment]
I am not sure it is better than now.

The documentation of query syntax and DDL syntax is separated, so they are written without concerning of confusion between them.

With `SchemaType` and `Type`, it's clear that the former is a type used in schemas.
However, with `DataType` and `Type`, that distinction becomes less clear and could lead to confusion.

ZetaSQL and Cloud Spanner Emulator don't use any name with `data_type` or `DataType` for `SchemaType` equivalent.

ZetaSQL: [`ASTColumnSchema`](https://github.com/google/zetasql/blob/master/zetasql/parser/gen_parse_tree.py#L8638-L8656)
Cloud Spanner Emulator: [`Type`](https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/blob/7ad3d598613bc6fef5ef9806bb5a3ee343f15586/backend/schema/ddl/operations.proto#L177) (FYI: Cloud Spanner Emulator don't use ZetaSQL for DDL)

I think `SchemaType` is a good enough name without causing any confusion. If necessary, we can add a doc comment saying that the type corresponds to the `data_type` in the DDL reference.

**Comment by makenowjust** [comment]
Ok. I understandd.
