### ISSUE TITLE
Proposal: Move to Cloud Spanner Ecosystem org

### ISSUE THREAD

**Issue by kazegusuri** [cloudspannerecosystem/memefish#51]
As I sent a message personally before, we are thinking to commit a spanner parser/analyzer with feature completes for improving our tooling as Mercari engineering. We have contributed to spansql in google-cloud-go recently because it seems more official as a spanner parser.  But spansql is not a library for spanner parser, it is a testing library and not intended for feature completes as a Spanner parser. So we started thinking to create a feature complete parser.

This library was developed as part of an intern program in Mercari. Our engineers sometimes contributed this project for our spanner libraries after it was published. If we can, it's the best to make this library feature completes as a spanner parser and we also want to add some utilities for handling DML/DSL to this library.

To make the contributions more easily and keep the maintenance, we would like to ask:

1. Move this repository into [cloudspannerecosystem](https://github.com/cloudspannerecosystem) org.
2. Add another maintainer for this repository.

For 1, it makes more wider engineers to see this library and may increase a chance to get contributions other companies. We have communicated with Spanner team in Google and they encourage to move spanner related OSSs to this org. 

For 2, it just aims to decrease the burden for reviews. We don't want to break the current direction of this library. Now you are the only owner/reviewer of this repository. We would like to help the maintenance if you want.

This is just just a proposal. Please let me know your opinions, thanks.

**Comment by makenowjust** [comment]
I apologize for the delayed response due to missing the message and this issue.

I agree with your proposal. I don't have enough time to maintain this library.
@tyamagu2 and @nktks have multiple contributions to this repository. I can recommend them to maintainers.

**Comment by tyamagu2** [comment]
Thank!. I'd like to be an maintainer then.

**Comment by nktks** [comment]
Thank you.

I can be a maintainer for small tasks such as adding features and bug fixes.
However, we would appreciate it if you could help with making a roadmap, reviewing big issues, PR, etc.

**Comment by kazegusuri** [comment]
@makenowjust We communicated with Spanner team. The teams asked to invite https://github.com/ansh0l as an owner of this repository to proceed the migration. Could you invite them?

Or if someone in the members above have the owner permissions in this repo, we can invite instead but it seems they don't have permissions in this repo. Please confirm the permission for them again.

**Comment by makenowjust** [comment]
At first, I invited @tyamagu2 and @nktks to be collaborators.

**Comment by kazegusuri** [comment]
Sorry I mean "admin" of repository. I thought even in a personal org, collaborators can admin for a repository.

> Why should I pass the ownership to someone? If you make me a member of [cloudspannerecosystem](https://github.com/cloudspannerecosystem) organization, I will do by myself the necessary work (transfer the repository to the organization, add maintainers, and set up permissions).

Even if we are a member of the org we don't have permissions to create a repo in the org. I am already the member but don't have the permission. It seems we need the permission to create a repo in the org to transfer repo. 
This is just the process we asked by team and we did the same process before for transfer.

**Comment by kazegusuri** [comment]
It seems we cannot add others as admin in a personal repository. I remembered there was a case that we transferred  a personal repo to the org. In the case we transferred the repo to Googler's personal org at first then they transferred it to spanner org.
I think you need to trust them in the case. If you want to communicate with him, please ask him the way of the migration. 
Anyway we need to confirm the way because we cannot add admin permission to google engineers.

**Comment by makenowjust** [comment]
Okay, I understand the process and trust @ansh0l. I will transfer the ownership to him.

**Comment by ansh0l** [comment]
@makenowjust : Thank you, I've made the three of you as maintainers, and moved the repo to cloudspannerecosystem org.
