### ISSUE TITLE
Turn on the update branch button for keeping PR fresh

### ISSUE THREAD

**Issue by git-hulk** [cloudspannerecosystem/memefish#67]
Hi @makenowjust

Would you mind turning on the `Update Branch` button in the project settings which would make it easier for contributors to keep the branch fresh with the lastest update(click the button)?

<img width="843" alt="image" src="https://github.com/cloudspannerecosystem/memefish/assets/4987594/5e73dd5c-f170-44c9-8a73-a84dc5303827">

**Comment by makenowjust** [comment]
Sorry. I have no privilege to turn on such settings.

@ansh0l @kazegusuri Could you help @git-hulk?

**Comment by git-hulk** [comment]
<img width="1290" alt="image" src="https://github.com/cloudspannerecosystem/memefish/assets/4987594/946f3584-9aac-4535-ac23-1671cbebcf5b">
@ansh0l @kazegusuri Cloud you help with it, what we need is to turn on the "Require branches to be up to date before merging" inside the branches settings. Thank you!

**Comment by makenowjust** [comment]
@git-hulk Sorry. I missed this setting and now I checked it.

<img width="1211" alt="スクリーンショット 2023-09-19 20 05 35" src="https://github.com/cloudspannerecosystem/memefish/assets/6679325/00257e73-3012-4559-8147-0dd63d32c0a3">

Does it help you?

**Comment by git-hulk** [comment]
@makenowjust Thank you! I think it will help.
