### ISSUE TITLE
Add FLOAT32 type support

### ISSUE THREAD

**Issue by apstndb** [cloudspannerecosystem/memefish#81]
It appears that the new primitive type `FLOAT32` is not yet supported.

https://cloud.google.com/spanner/docs/release-notes#April_09_2024

>Spanner now supports the float32 ([GoogleSQL](https://cloud.google.com/spanner/docs/reference/standard-sql/data-types#floating_point_types)) and float4/real ([PostgreSQL](https://cloud.google.com/spanner/docs/reference/postgresql/data-types#supported)) data type (in [Preview](https://cloud.google.com/products#product-launch-stages)).

**Comment by makenowjust** [comment]
I created a new pull request #82.
