### ISSUE TITLE
Duplicate code when parsing OPTIONS items

### ISSUE THREAD

**Issue by git-hulk** [cloudspannerecosystem/memefish#83]
Currently, Spanner supports creating the [vector index](https://cloud.google.com/spanner/docs/reference/standard-sql/data-definition-language#create_vector_index) for a table and I'm planning to support the corresponding syntax in memefish. 

Meanwhile, I found that we now have two places support `OPTIONS(k=v, k=v,...)` in `CREATE SEQUENCE` and `CREATE CHANGE STREAM`:

- [SequenceOption](https://github.com/cloudspannerecosystem/memefish/blob/f34cb1043dcef5584a332706e371a07da1816a4b/ast/ast.go#L2321)
- [ChangeStreamOptionsRecord](https://github.com/cloudspannerecosystem/memefish/blob/f34cb1043dcef5584a332706e371a07da1816a4b/ast/ast.go#L1898)

We are now using the specific prefix for the option, and it needs to introduce another one for CREATE VECTOR INDEX which also supports parsing OPTIONS. It will also introduce a lot of duplicates as more and more statements support parsing options.

So I think if it's good to reduce `SequenceOption` and `ChangeStreamOptionsRecord` into a single one? 

```Go
type Options struct {
    // pos = Options
    // end = Rparen + 1

    Options token.Pos // position of "OPTIONS" keyword
    Rparen  token.Pos // position of ")"

    Records []*Option // len(Records) > 0
}


type Option struct {
    // pos = Key.pos
    // end = Value.end

    Key   *Ident
    Value Expr
}
```

**Comment by git-hulk** [comment]
@makenowjust What do you think about this?

**Comment by makenowjust** [comment]
We also have `ColumnDefOptions`, so there is no problem with code duplication. Let's create a new struct with an explicit name!

**Comment by git-hulk** [comment]
> We also have ColumnDefOptions, so there is no problem with code duplication. Let's create a new struct with an explicit name!

Yes, ColumnDefOptions is another option pattern. I will keep the current pattern to implement CREATE VECTOR INDEX. Thank you!
