### ISSUE TITLE
Deploy docs CI is broken due to missing secrets in GitHub Actions

### ISSUE THREAD

**Issue by git-hulk** [cloudspannerecosystem/memefish#86]
Seems `ACTIONS_DEPLOY_KEY` was removed from secrets a few months ago, and it caused the CI failure while deploying the documentation. I'm not sure if it's an expected operation. Perhaps we can replace the deploy key with GITHUB TOKEN?

CI error: https://github.com/cloudspannerecosystem/memefish/actions/runs/10472793495/job/29003115616

**Comment by makenowjust** [comment]
@ansh0l or anyone who has admin permission for this repo.

I changed gh-pages deploy workflow in #87 (7005cc7), but we also need to change GitHub settings to work this change.

Please fix GitHub settings to publish GitHub pages from GitHub Actions workflow according to [this doc](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-with-a-custom-github-actions-workflow) 🙏

**Comment by git-hulk** [comment]
Yes, I have confirmed that works well after setting the gh-pages source:

https://github.com/git-hulk/memefish/actions/runs/10484583362

- Setting source to GitHub Actions
<img width="1576" alt="image" src="https://github.com/user-attachments/assets/78b387fc-5819-4c49-b1e4-23daaa28265b">

- Check if the branch is main

<img width="1351" alt="image" src="https://github.com/user-attachments/assets/9236f7bf-6251-4b59-9be0-48d7dac0308a">

**Comment by makenowjust** [comment]
Now, GitHub Pages deployment workflow works, but the layout seems broken.

Then, I created #103 to switch to use [techdoc](https://themes.gohugo.io/themes/hugo-theme-techdoc/) for Hugo theme.
